### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by ppigazzini** [jromang/fishbuilder#1]
Inconsistency (starting space)
https://github.com/jromang/fishbuilder/blob/fec65348efbcaaceb301ee86558e72e79d611616/fishbuilder.py#L88

Typo
https://github.com/jromang/fishbuilder/blob/fec65348efbcaaceb301ee86558e72e79d611616/fishbuilder.py#L100

**Comment by jromang** [comment]
Thanks !
